// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqCexAHGHxS-lqHfoZxS6YYXV7KyCvwQ',
    appId: '1:760594344892:web:272b6d0517c5b8728919b9',
    messagingSenderId: '760594344892',
    projectId: 'lost-link-2064',
    authDomain: 'lost-link-2064.firebaseapp.com',
    storageBucket: 'lost-link-2064.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUi7UwCPH3_N5UVygzLB6JRvb4vm2lLWc',
    appId: '1:760594344892:android:19da0cb8ecf37aee8919b9',
    messagingSenderId: '760594344892',
    projectId: 'lost-link-2064',
    storageBucket: 'lost-link-2064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvucndUb6c5bHPvKTsa9K-s5gC25XPNM',
    appId: '1:760594344892:ios:1d95b3c6844693b18919b9',
    messagingSenderId: '760594344892',
    projectId: 'lost-link-2064',
    storageBucket: 'lost-link-2064.firebasestorage.app',
    iosBundleId: 'com.example.lostLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAvucndUb6c5bHPvKTsa9K-s5gC25XPNM',
    appId: '1:760594344892:ios:1d95b3c6844693b18919b9',
    messagingSenderId: '760594344892',
    projectId: 'lost-link-2064',
    storageBucket: 'lost-link-2064.firebasestorage.app',
    iosBundleId: 'com.example.lostLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyqCexAHGHxS-lqHfoZxS6YYXV7KyCvwQ',
    appId: '1:760594344892:web:b9cbb63e1c76c9058919b9',
    messagingSenderId: '760594344892',
    projectId: 'lost-link-2064',
    authDomain: 'lost-link-2064.firebaseapp.com',
    storageBucket: 'lost-link-2064.firebasestorage.app',
  );
}
